module Base.Nat.ALL where

open import Base.Nat.Nat public
open import Base.Nat.Trait.Add public
open import Base.Nat.Trait.Eq public
open import Base.Nat.Trait.Ord public
open import Base.Nat.Trait.Show public
open import Base.Nat.add public
open import Base.Nat.compare public
open import Base.Nat.div.go public
open import Base.Nat.div public
open import Base.Nat.double public
open import Base.Nat.eq public
open import Base.Nat.exp public
open import Base.Nat.gt public
open import Base.Nat.gte public
open import Base.Nat.half public
open import Base.Nat.is-zero public
open import Base.Nat.lt public
open import Base.Nat.lte public
open import Base.Nat.match public
open import Base.Nat.max public
open import Base.Nat.min public
open import Base.Nat.mod public
open import Base.Nat.mul public
open import Base.Nat.neq public
open import Base.Nat.pred public
open import Base.Nat.range public
open import Base.Nat.rshift public
open import Base.Nat.show public
open import Base.Nat.sub public
open import Base.Nat.to-bits public
open import Base.Nat.to-u64 public
open import Base.Nat.xor public
