module Bend.is-generated-name where

open import Base.Bool.Bool
open import Base.Bool.or
open import Base.String.String
open import Base.String.contains

-- Checks if a name is generated by looking for substrings that only occur in generated names.
-- - name: The string to check.
-- = True if the name is generated, False otherwise.
is-generated-name : String → Bool
is-generated-name name = (contains name "__") || (contains name "%")
