"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.E = exports.$E = exports.I = exports.$I = exports.O = exports.$O = void 0;
const $O = (tail) => ({ $: 'O', tail });
exports.$O = $O;
const O = (tail) => (0, exports.$O)(tail);
exports.O = O;
const $I = (tail) => ({ $: 'I', tail });
exports.$I = $I;
const I = (tail) => (0, exports.$I)(tail);
exports.I = I;
exports.$E = { $: 'E' };
exports.E = exports.$E;
